export const mowers = [
  {
    name: 'Kosiarka spalinowa GV 44 PK OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/6618-large_default/kosiarka-spalinowa-gv-44-pk-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gv-44-pk-oleo-mac.html',
    brand: 'EMAK',
    width: '41',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka akumulatorowa GI 48 P-2x5 OLEO-MAC + zestaw (2x akumulator i ładowarka)',
    imageURL:
      'https://www.ogrod-dom.pl/6705-large_default/kosiarka-akumulatorowa-gi-48-p-2x5-oleo-mac-zestaw-2x-akumulator-i-ladowarka.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-akumulatorowa-gi-48-p-2x5-oleo-mac-zestaw-2x-akumulator-i-ladowarka.html',
    brand: 'EMAK',
    width: '46',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka akumulatorowa GI 48 P-5 OLEO-MAC + zestaw (akumulator i ładowarka)',
    imageURL:
      'https://www.ogrod-dom.pl/6701-large_default/kosiarka-akumulatorowa-gi-48-p-5-oleo-mac-zestaw-akumulator-i-ladowarka.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-akumulatorowa-gi-48-p-5-oleo-mac-zestaw-akumulator-i-ladowarka.html',
    brand: 'EMAK',
    width: '46',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka akumulatorowa GI 44 P OLEO-MAC + zestaw (akumulator, ładowarka)',
    imageURL:
      'https://www.ogrod-dom.pl/6635-large_default/kosiarka-akumulatorowa-gi-44-p-oleo-mac-zestaw-akumulator-ladowarka.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-akumulatorowa-gi-44-p-oleo-mac-zestaw-akumulator-ladowarka.html',
    brand: 'EMAK',
    width: '41',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GV 48 TK Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/6620-large_default/kosiarka-spalinowa-gv-48-tk-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gv-48-tk-allroad4-oleo-mac.html',
    brand: 'EMAK',
    width: '46',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna K35P OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/2020-large_default/kosiarka-elektryczna-k35p-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-k35p-oleo-mac.html',
    brand: 'EMAK',
    width: '33',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna IERM 1434 IKRA',
    imageURL:
      'https://www.ogrod-dom.pl/3-large_default/kosiarka-elektryczna-ierm-1434-ikra.jpg',
    href: 'https://www.ogrod-dom.pl/kosiarki-elektryczne/kosiarka-elektryczna-ierm-1434-ikra.html',
    brand: 'EMAK',
    width: '34',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna IERM 1638 IKRA',
    imageURL:
      'https://www.ogrod-dom.pl/6625-large_default/kosiarka-elektryczna-ierm-1638-ikra.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-ierm-1638-ikra.html',
    brand: 'EMAK',
    width: '38',
    drive: false,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka akumulatorowa LM3 E40 CUB CADET + zestaw (akumulator i ładowarka)',
    imageURL:
      'https://www.ogrod-dom.pl/6709-large_default/kosiarka-akumulatorowa-lm3-e40-cub-cadet-zestaw-akumulator-i-ladowarka.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-akumulatorowa-lm3-e40-cub-cadet-zestaw-akumulator-i-ladowarka.html',
    brand: 'EMAK',
    width: '40',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GV 48 PK Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3413-large_default/kosiarka-spalinowa-gv-48-pk-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gv-48-pk-allroad4-oleo-mac.html',
    brand: 'EMAK',
    width: '46',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GV 44 TK OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/6619-large_default/kosiarka-spalinowa-gv-44-tk-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gv-44-tk-oleo-mac.html',
    brand: 'EMAK',
    width: '41',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna IELM 1232 IKRA',
    imageURL:
      'https://www.ogrod-dom.pl/4022-large_default/kosiarka-elektryczna-ielm-1232-ikra.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-ielm-1232-ikra.html',
    brand: 'EMAK',
    width: '32',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GV 53 TK Allroad4 E OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3415-large_default/kosiarka-spalinowa-gv-53-tk-allroad4-e-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gv-53-tk-allroad4-e-oleo-mac.html',
    brand: 'EMAK',
    width: '51',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna A 340 E WOLF-Garten',
    imageURL:
      'https://www.ogrod-dom.pl/2027-large_default/kosiarka-elektryczna-a-340-e-wolf-garten.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-a-340-e-wolf-garten.html',
    brand: 'EMAK',
    width: '34',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GMC 48 TKE Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3184-large_default/kosiarka-spalinowa-gmc-48-tke-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gmc-48-tke-allroad4-oleo-mac.html',
    brand: 'EMAK',
    width: '46',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna S 3800 E WOLF-Garten',
    imageURL:
      'https://www.ogrod-dom.pl/2026-large_default/kosiarka-elektryczna-s-3800-e-wolf-garten.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-s-3800-e-wolf-garten.html',
    brand: 'EMAK',
    width: '38',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa G 44 PK Comfort OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3419-large_default/kosiarka-spalinowa-g-44-pk-comfort-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-g-44-pk-comfort-oleo-mac.html',
    brand: 'EMAK',
    width: '41',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna S 3200 E WOLF-Garten',
    imageURL:
      'https://www.ogrod-dom.pl/2025-large_default/kosiarka-elektryczna-s-3200-e-wolf-garten.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-s-3200-e-wolf-garten.html',
    brand: 'EMAK',
    width: '32',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GV 53 TBX Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3417-large_default/kosiarka-spalinowa-gv-53-tbx-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gv-53-tbx-allroad4-oleo-mac.html',
    brand: 'Briggs&Stratton',
    width: '51',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna K40P OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/2021-large_default/kosiarka-elektryczna-k40p-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-k40p-oleo-mac.html',
    brand: 'Briggs&Stratton',
    width: '38',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna G 48 PE Comfort OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/4020-large_default/kosiarka-elektryczna-g-48-pe-comfort-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-g-48-pe-comfort-oleo-mac.html',
    brand: 'Briggs&Stratton',
    width: '46',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GV 53 TK Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3408-large_default/kosiarka-spalinowa-gv-53-tk-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gv-53-tk-allroad4-oleo-mac.html',
    brand: 'EMAK',
    width: '51',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GV 53 PK Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3411-large_default/kosiarka-spalinowa-gv-53-pk-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/kosiarki-spalinowe/kosiarka-spalinowa-gv-53-pk-allroad4-oleo-mac.html',
    brand: 'EMAK',
    width: '51',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna G 44 PE Comfort OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/4021-large_default/kosiarka-elektryczna-g-44-pe-comfort-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-g-44-pe-comfort-oleo-mac.html',
    brand: 'EMAK',
    width: '41',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna A 370 E WOLF-Garten',
    imageURL:
      'https://www.ogrod-dom.pl/2028-large_default/kosiarka-elektryczna-a-370-e-wolf-garten.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-a-370-e-wolf-garten.html',
    brand: 'EMAK',
    width: '37',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna Silver 4.64 E Comfort 113103 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/4036-large_default/kosiarka-elektryczna-silver-464-e-comfort-113103-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-silver-464-e-comfort-113103-al-ko.html',
    brand: 'EMAK',
    width: '46',
    drive: false,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa V53H200 VICTUS',
    imageURL:
      'https://www.ogrod-dom.pl/4019-large_default/KosiarkaspalinowaV53H200VICTUS.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/KosiarkaspalinowaV53H200VICTUS.html',
    brand: 'EMAK',
    width: '53',
    drive: true,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna 4.27 E Plus Classic 112998 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/4031-large_default/kosiarka-elektryczna-427-e-plus-classic-112998-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-427-e-plus-classic-112998-al-ko.html',
    brand: 'EMAK',
    width: '42',
    drive: false,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa V51H170 VICTUS',
    imageURL:
      'https://www.ogrod-dom.pl/4018-large_default/kosiarka-spalinowa-v51h170-victus.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-v51h170-victus.html',
    brand: 'EMAK',
    width: '51',
    drive: true,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GMC 53 THX Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3215-large_default/kosiarka-spalinowa-gmc-53-thx-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gmc-53-thx-allroad4-oleo-mac.html',
    brand: 'Honda',
    width: '51',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna 34 E Silver Comfort 112857 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/4025-large_default/kosiarka-elektryczna-34-e-silver-comfort-112857-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-34-e-silver-comfort-112857-al-ko.html',
    brand: 'Honda',
    width: '34',
    drive: false,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa GMC 53 TKE Allroad4 OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/3204-large_default/kosiarka-spalinowa-gmc-53-tke-allroad4-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-gmc-53-tke-allroad4-oleo-mac.html',
    brand: 'EMAK',
    width: '51',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna  3.87 E Plus Classic 113527 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/4973-large_default/kosiarka-elektryczna-387-e-plus-classic-113527-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-387-e-plus-classic-113527-al-ko.html',
    brand: 'EMAK',
    width: '38',
    drive: false,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka elektryczna A 400 E WOLF-Garten',
    imageURL:
      'https://www.ogrod-dom.pl/2029-large_default/kosiarka-elektryczna-a-400-e-wolf-garten.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-elektryczna-a-400-e-wolf-garten.html',
    brand: 'EMAK',
    width: '40',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa G 44 TK Comfort Graphite OLEO-MAC',
    imageURL:
      'https://www.ogrod-dom.pl/1032-large_default/kosiarka-spalinowa-g-44-tk-comfort-graphite-oleo-mac.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-g-44-tk-comfort-graphite-oleo-mac.html',
    brand: 'EMAK',
    width: '41',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa LM1 DP53 CUB CADET',
    imageURL:
      'https://www.ogrod-dom.pl/1039-large_default/kosiarka-spalinowa-lm1-dp53-cub-cadet.jpg',
    href: 'https://www.ogrod-dom.pl/maszyny-ogrodnicze/kosiarka-spalinowa-lm1-dp53-cub-cadet.html',
    brand: 'Cub Cadet',
    width: '53',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa 520 VSI-B Premium 119948 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/4049-large_default/kosiarka-spalinowa-520-vsi-b-premium-119948-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-520-vsi-b-premium-119948-al-ko.html',
    brand: 'Cub Cadet',
    width: '51',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa 470 VS-B Premium 119947 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/4039-large_default/kosiarka-spalinowa-470-vs-b-premium-119947-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-470-vs-b-premium-119947-al-ko.html',
    brand: 'Cub Cadet',
    width: '46',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa 470 SPI-A Premium AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/1051-large_default/kosiarka-spalinowa-470-spi-a-premium-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-470-spi-a-premium-al-ko.html',
    brand: 'Cub Cadet',
    width: '46',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa 470 SP-H Premium 119968 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/4048-large_default/kosiarka-spalinowa-470-sp-h-premium-119968-al-ko-.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-470-sp-h-premium-119968-al-ko-.html',
    brand: 'Cub Cadet',
    width: '46',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa 4.2 P-S Easy 113794 AL-KO',
    imageURL:
      'https://www.ogrod-dom.pl/6626-large_default/kosiarka-spalinowa-42-p-s-easy-113794-al-ko.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-42-p-s-easy-113794-al-ko.html',
    brand: 'Cub Cadet',
    width: '42',
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa XM1 DR46 CUB CADET',
    imageURL:
      'https://www.ogrod-dom.pl/3004-large_default/kosiarka-spalinowa-xm1-dr46-cub-cadet.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-xm1-dr46-cub-cadet.html',
    brand: 'Cub Cadet',
    width: '46',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka akumulatorowa 2x20V PowerShare WG743E WORX + zestaw (2x akumulator i ładowarka)',
    imageURL:
      'https://www.ogrod-dom.pl/6630-large_default/kosiarka-akumulatorowa-2x20v-powershare-wg743e-worx-zestaw-2x-akumulator-i-ladowarka.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-akumulatorowa-2x20v-powershare-wg743e-worx-zestaw-2x-akumulator-i-ladowarka.html',
    brand: 'Cub Cadet',
    width: '40',
    drive: false,
    basket: false,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa LM3 DR53ES CUB CADET',
    imageURL:
      'https://www.ogrod-dom.pl/3001-large_default/kosiarka-spalinowa-lm3-dr53es-cub-cadet.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-lm3-dr53es-cub-cadet.html',
    brand: 'Cub Cadet',
    width: '53',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka spalinowa LM3 CRC46S CUB CADET',
    imageURL:
      'https://www.ogrod-dom.pl/1043-large_default/kosiarka-spalinowa-lm3-crc46s-cub-cadet.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-spalinowa-lm3-crc46s-cub-cadet.html',
    brand: 'Cub Cadet',
    width: '46',
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'Kosiarka akumulatorowa 2x20V PowerShare WG779E WORX + zestaw (2x akumulator i ładowarka)',
    imageURL:
      'https://www.ogrod-dom.pl/4341-large_default/kosiarka-akumulatorowa-2x20v-powershare-wg779e-worx-zestaw-2x-akumulator-i-ladowarka.jpg',
    href: 'https://www.ogrod-dom.pl/oferta-kategorie/kosiarka-akumulatorowa-2x20v-powershare-wg779e-worx-zestaw-2x-akumulator-i-ladowarka.html',
    brand: 'Cub Cadet',
    width: '34',
    drive: false,
    basket: false,
    discharge: false,
  },
];
export const brands = Array.from(
  new Set(mowers.map(({ brand }) => brand))
).sort();

export const widths = Array.from(
  new Set(mowers.map(({ width }) => width))
).sort();
