export const brands = [
  'AL-KO',
  'Briggs&Strratton',
  'Cub Cadet',
  'Emak',
  'Honda',
];

export const widths = [
  '18 cm',
  '28 cm',
  '32 cm',
  '33 cm',
  '34 cm',
  '37 cm',
  '38 cm',
  '40 cm',
  '41 cm',
  '42 cm',
  '46 cm',
  '51 cm',
  '53 cm',
];

export const mowers = [
  {
    name: 'lorem ipsum dolor sit ammet',
    image: 'https://picsum.photos/300/200',
    href: '/',
    brand: 'AL-KO',
    width: 18,
    drive: false,
    basket: false,
    discharge: false,
  },
  {
    name: 'lorem ipsum dolor aluminum can',
    image: 'https://picsum.photos/300/200',
    href: '/',
    brand: 'Honda',
    width: 51,
    drive: false,
    basket: true,
    discharge: false,
  },
  {
    name: 'coins dolor sit ammet',
    image: 'https://picsum.photos/300/200',
    href: '/',
    brand: 'Honda',
    width: 53,
    drive: false,
    basket: false,
    discharge: true,
  },
  {
    name: 'lorem ipsum conditioner ammet',
    image: 'https://picsum.photos/300/200',
    href: '/',
    brand: 'Cub Cadet',
    width: 38,
    drive: true,
    basket: false,
    discharge: false,
  },
  {
    name: 'air freshener dolor sit ammet',
    image: 'https://picsum.photos/300/200',
    href: '/',
    brand: 'Briggs&Strratton',
    width: 18,
    drive: true,
    basket: true,
    discharge: true,
  },
  {
    name: 'ldoleam ipsum dolor sit ammet',
    image: 'https://picsum.photos/300/200',
    href: '/',
    brand: 'Briggs&Strratton',
    width: 40,
    drive: true,
    basket: true,
    discharge: false,
  },
  {
    name: 'ldoleam ipsum pool cue ammet',
    image: 'https://picsum.photos/300/200',
    href: '/',
    brand: 'AL-KO',
    width: 18,
    drive: true,
    basket: false,
    discharge: true,
  },
];
